name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make
    
    - name: Build and run tests
      run: |
        make run-tests
    
    - name: Test result
      run: |
        echo "✅ CI Tests completed successfully!"
        echo "📋 All tests passed"
